on:
  rss:
    url: https://rss.golem.de/rss.php?feed=RSS2.0
    config:
      filter:
        content:
            $regex: ....+
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs Eins
        env:
          title: ${{on.rss.outputs.title}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          content: ${{on.rss.outputs.content}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo contentSnippet: $contentSnippet
          echo content: $content
          echo link: $link
