on:
  rss:
    url: https://rss.evangelizo.org/rss/v2/evangelizo_rss-de.xml
    config:
      format: |
        item.contentSnippet = item.guid.substring(0,10)
        return item;
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
        run: |
          echo contentSnippet: $contentSnippet
